# Generated by Django 2.0.2 on 2020-03-05 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_remove_product_icon'),
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdingmutualsip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('no_shares', models.FloatField(default=None)),
                ('invest_amount', models.IntegerField(default=None)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holdingmutual',
            name='investment_type',
            field=models.CharField(blank=True, default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='holdingmutual',
            name='notes',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='holdingmutual',
            name='sip_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='holdingmutual',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
