# Generated by Django 2.0.2 on 2019-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingmutual',
            name='notes',
            field=models.TextField(blank=True, default=None),
        ),
    ]
