# Generated by Django 2.0.2 on 2020-03-06 05:17

from django.db import migrations, models
import holdings.models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_auto_20200305_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingmutualsip',
            name='no_shares',
        ),
        migrations.AlterField(
            model_name='holdingmutualsip',
            name='date',
            field=models.DateField(default=holdings.models.Holdingmutualsip.return_date_time),
        ),
    ]
