# Generated by Django 2.0.2 on 2019-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_auto_20190117_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingmutual',
            name='sip_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='holdingmutual',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
