# Generated by Django 2.0.2 on 2020-03-06 05:19

from django.db import migrations, models
import holdings.models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_auto_20200306_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingmutualsip',
            name='end_date',
            field=models.DateField(default=holdings.models.Holdingmutualsip.return_date_time),
        ),
        migrations.AlterField(
            model_name='holdingmutualsip',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
