# Generated by Django 2.0.2 on 2019-01-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190115_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='to_date',
        ),
    ]
